//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negocio.WsCesfam {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsCesfam.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAdmin", ReplyAction="http://tempuri.org/IService1/getAdminResponse")]
        string getAdmin();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getAdmin", ReplyAction="http://tempuri.org/IService1/getAdminResponse")]
        System.Threading.Tasks.Task<string> getAdminAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getControlStock", ReplyAction="http://tempuri.org/IService1/getControlStockResponse")]
        string getControlStock();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getControlStock", ReplyAction="http://tempuri.org/IService1/getControlStockResponse")]
        System.Threading.Tasks.Task<string> getControlStockAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDetForm", ReplyAction="http://tempuri.org/IService1/getDetFormResponse")]
        string getDetForm();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getDetForm", ReplyAction="http://tempuri.org/IService1/getDetFormResponse")]
        System.Threading.Tasks.Task<string> getDetFormAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFormMedicamentos", ReplyAction="http://tempuri.org/IService1/getFormMedicamentosResponse")]
        string getFormMedicamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getFormMedicamentos", ReplyAction="http://tempuri.org/IService1/getFormMedicamentosResponse")]
        System.Threading.Tasks.Task<string> getFormMedicamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getLaboratorio", ReplyAction="http://tempuri.org/IService1/getLaboratorioResponse")]
        string getLaboratorio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getLaboratorio", ReplyAction="http://tempuri.org/IService1/getLaboratorioResponse")]
        System.Threading.Tasks.Task<string> getLaboratorioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getMedicamentos", ReplyAction="http://tempuri.org/IService1/getMedicamentosResponse")]
        string getMedicamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getMedicamentos", ReplyAction="http://tempuri.org/IService1/getMedicamentosResponse")]
        System.Threading.Tasks.Task<string> getMedicamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getMedico", ReplyAction="http://tempuri.org/IService1/getMedicoResponse")]
        string getMedico();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getMedico", ReplyAction="http://tempuri.org/IService1/getMedicoResponse")]
        System.Threading.Tasks.Task<string> getMedicoAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Negocio.WsCesfam.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Negocio.WsCesfam.IService1>, Negocio.WsCesfam.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string getAdmin() {
            return base.Channel.getAdmin();
        }
        
        public System.Threading.Tasks.Task<string> getAdminAsync() {
            return base.Channel.getAdminAsync();
        }
        
        public string getControlStock() {
            return base.Channel.getControlStock();
        }
        
        public System.Threading.Tasks.Task<string> getControlStockAsync() {
            return base.Channel.getControlStockAsync();
        }
        
        public string getDetForm() {
            return base.Channel.getDetForm();
        }
        
        public System.Threading.Tasks.Task<string> getDetFormAsync() {
            return base.Channel.getDetFormAsync();
        }
        
        public string getFormMedicamentos() {
            return base.Channel.getFormMedicamentos();
        }
        
        public System.Threading.Tasks.Task<string> getFormMedicamentosAsync() {
            return base.Channel.getFormMedicamentosAsync();
        }
        
        public string getLaboratorio() {
            return base.Channel.getLaboratorio();
        }
        
        public System.Threading.Tasks.Task<string> getLaboratorioAsync() {
            return base.Channel.getLaboratorioAsync();
        }
        
        public string getMedicamentos() {
            return base.Channel.getMedicamentos();
        }
        
        public System.Threading.Tasks.Task<string> getMedicamentosAsync() {
            return base.Channel.getMedicamentosAsync();
        }
        
        public string getMedico() {
            return base.Channel.getMedico();
        }
        
        public System.Threading.Tasks.Task<string> getMedicoAsync() {
            return base.Channel.getMedicoAsync();
        }
    }
}
